source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!


target 'Netflix' do
  # Comment the next line if you don't want to use dynamic frameworks
    
  pod 'SDWebImageSwiftUI'
  pod 'R.swift'
  pod 'GSPlayer'

  # Pods for Netflix

end
